# Generated by Django 5.0.1 on 2025-11-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
