# Generated by Django 5.0.1 on 2025-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
