# Generated by Django 5.0.1 on 2025-11-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_zoomcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_client_id', models.CharField(blank=True, default='', max_length=200)),
                ('zoom_client_secret', models.CharField(blank=True, default='', max_length=400)),
                ('zoom_redirect_uri', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
