# Generated by Django 5.0.1 on 2025-11-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mentorzoomapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorzoomapp',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlatformSettings',
        ),
        migrations.RemoveField(
            model_name='zoomcredential',
            name='user',
        ),
        migrations.DeleteModel(
            name='MentorZoomApp',
        ),
        migrations.DeleteModel(
            name='ZoomCredential',
        ),
    ]
